# Generated by Django 4.1.7 on 2023-04-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0002_remove_favourite_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
