# Generated by Django 4.1.7 on 2023-05-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_manual_slug',
            field=models.BooleanField(default=False),
        ),
    ]
