# Generated by Django 4.1.7 on 2023-04-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_categories_product_products_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
