# Generated by Django 4.1.7 on 2023-04-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
    ]
