# Generated by Django 4.1.7 on 2023-04-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_favoriteproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteProduct',
        ),
    ]
